<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class DatacsvsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('datacsvs')->insert([

           [
                'code' => 'Б0001471',
                'name' => 'Вентилятор осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import',
                'level_two' => 'Модульные системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8088',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001472',
                'name' => 'Вентилятор2 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import2',
                'level_two' => 'Модульные2 системы вентиляции',
                'level_three' => '',
                'price' => '347',
                'priceSP' => '75',
                'quantity' => '333',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8043',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],
           [
                'code' => 'Б0001473',
                'name' => 'Вентилятор3 осевой вытяжной с сеткой D 125 (ERA 5S)',
                'level_one' => 'Import3',
                'level_two' => 'Модульные3 системы вентиляции',
                'level_three' => '',
                'price' => '346',
                'priceSP' => '75',
                'quantity' => '339',
                'properties' => '45',
                'joint_sale' => '',
                'unit' => 'шт',
                'picture' => '_MG_8082',
                'home' => '',
                'description' => '0',
           ],

       ]);
    }
}
